---
title: "Final Memo"
subtitle: "Data Visualization (STAT 302)"
author: "Shruti Rathnavel"
output:
  html_document:
    toc: yes
    toc_float: yes
    highlight: "tango"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dataset

I worked with transport related census data from the National Historical GIS Database at the University of Michigan - link to the whole database here: https://data2.nhgis.org/. I originally had planned to more broadly explore the census data (as I described in my data memo), but I decided to focus specifically on transport once I was able to find a suitable dataset at the census-tract level. I was partly inspired by some visualizations made by geographer Christopher Winters, which can be found at https://www.liberallandscape.org/2021/09/29/the-geography-of-carfree-households-in-the-united-states/, but I wanted to focus on different types of transit and also on whether people resorted to working from home based on proximity to urban centers (this was census data from 2015 - 2019, so work from home patterns in this data were not affected by the pandemic).

## Shiny Interface

I originally was going to focus just on car, public transit, and work from home percentages in Chicago. However, I found that the visualizations and data were pretty easily reproducible across different cities (or more accurately counties) and realized I could produce visualizations of different cities and allow for more nuance in describing how people traveled by making an interactive dashboard. I preferred the `shiny` format over a long-form report with a series of different maps.

## Visualizations

These visualizations explore the distribution of commuters around urban centers by mode of transport. As expected, they show that the vast majority of people drive to work - although this changes very close to downtowns. Bus use appears to follow the opposite trend - people who travel by bus live closer to urban centers. Trains are a matter of interest, especially in Chicago - people who commute by train are clustered around downtown, but there appear to be corridors moving out from downtown Chicago where more people use the train - which quite possibly corresponds to the CTA. The distribution looks kind of similar to the CTA map, with higher percentages of train commuters clustered around the Loop. I know less about LA and New York, so it's more difficult to make inferences without spatial context. For this reason, I added basemap options - the streetmap view makes roads and railway lines visible, so this relationship between proximity to trains and commuting by train becomes easier to explore.

Another interesting thing is the distribution of people who work from home, which appears to be more random or at least less driven by proximity to urban areas. People who live further from the city do not seem to be more likely to work from home. However, the map of people working from home in Chicago is once again interesting because more people to the north of the city seem to be able to work from home. Because I had some context regarding spatial income distributions in Chicago, it appeared fairly obvious that people living in wealthier areas are more likely to work from home. I created some visualizations of median income in `mapview` under misc-visualizations.R similar to the one we did in class just to compare income and work-from-home distribution in all three cities, and found that the maps seemed to capture similar trends in distribution. I made the median income visible in my visualizations by setting the popup argument under `mapview` so that median income data from `tidycensus` for that census tract pops up when you click on a census tract. This makes it easier to look at the relationship between income and transport in my visualizations. 

## App

I published the app, and it can be found at https://shruti820.shinyapps.io/TransportApp/

The only remaining issue with the app is that because popup data is so large for LA and Chicago in particular, when you access the app from the above link the popups and labels do not work for those two cities - though it works for New York City. I think that may be either a data limit imposed on shiny users using the site for free, or I just have to wait longer for the entire app to load.




